name: knockout_tournament
description: "Knockout Tournament app"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  hive_flutter: ^1.1.0
  flutter_launcher_icons: ^0.14.3
  flutter_inset_shadow: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  hive_generator: ^2.0.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo/logo.png"
  adaptive_icon_background: "#FF000000"
  adaptive_icon_foreground: "assets/logo/logo.png"
  android_inset: true
  ios_inset: true


flutter:

  uses-material-design: true
  assets:
    - assets/bg_images/
    - assets/logo/
    - assets/icons/
    - assets/profiles/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
